language: python
python: 3.7
dist: xenial
sudo: true

services:
  - redis-server

before_install:
  - cp .env.sample .env
  - pip install -r requirements.txt

script:
  - pytest
  - black . --check

after_success:
  - codecov
